In [124]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from matplotlib import pyplot as plt

In [125]:
base_census = pd.read_csv('/content/drive/MyDrive/Projetos/ML/Census and Base_credit/census.csv')

In [126]:
base_census.head()

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K

[5 rows x 15 columns]

In [127]:
base_census.describe()

age  final-weight  ...  capital-loos  hour-per-week
count  32561.000000  3.256100e+04  ...  32561.000000   32561.000000
mean      38.581647  1.897784e+05  ...     87.303830      40.437456
std       13.640433  1.055500e+05  ...    402.960219      12.347429
min       17.000000  1.228500e+04  ...      0.000000       1.000000
25%       28.000000  1.178270e+05  ...      0.000000      40.000000
50%       37.000000  1.783560e+05  ...      0.000000      40.000000
75%       48.000000  2.370510e+05  ...      0.000000      45.000000
max       90.000000  1.484705e+06  ...   4356.000000      99.000000

[8 rows x 6 columns]

In [128]:
X_census = base_census.iloc[:, 0:14]

In [129]:
X_census

age          workclass  ...  hour-per-week  native-country
0       39          State-gov  ...             40   United-States
1       50   Self-emp-not-inc  ...             13   United-States
2       38            Private  ...             40   United-States
3       53            Private  ...             40   United-States
4       28            Private  ...             40            Cuba
...    ...                ...  ...            ...             ...
32556   27            Private  ...             38   United-States
32557   40            Private  ...             40   United-States
32558   58            Private  ...             40   United-States
32559   22            Private  ...             20   United-States
32560   52       Self-emp-inc  ...             40   United-States

[32561 rows x 14 columns]

In [130]:
y_census = base_census.iloc[: , 14]

In [131]:
y_census

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
32556     <=50K
32557      >50K
32558     <=50K
32559     <=50K
32560      >50K
Name: income, Length: 32561, dtype: object

In [132]:
le = LabelEncoder()

In [133]:
X_census.apply(le.fit_transform)

age  workclass  ...  hour-per-week  native-country
0       22          7  ...             39              39
1       33          6  ...             12              39
2       21          4  ...             39              39
3       36          4  ...             39              39
4       11          4  ...             39               5
...    ...        ...  ...            ...             ...
32556   10          4  ...             37              39
32557   23          4  ...             39              39
32558   41          4  ...             39              39
32559    5          4  ...             19              39
32560   35          5  ...             39              39

[32561 rows x 14 columns]

In [134]:
ohe = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,3,5,6,7,8,9,13])], remainder='passthrough')

In [135]:
X_census = ohe.fit_transform(X_census).toarray()

In [136]:
X_census

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

In [137]:
X_census.shape

(32561, 108)

In [138]:
GB = GaussianNB()

In [139]:
X_train, X_test, y_train, y_test = train_test_split(X_census, y_census, test_size = 0.3, random_state=0)

In [140]:
y_predict = GB.fit(X_train, y_train).predict(X_test)

In [141]:
ac_naive = accuracy_score(y_test, y_predict)
ac_naive

0.7974204115057836

In [142]:
confusion_matrix(y_test, y_predict)

array([[7041,  366],
       [1613,  749]])

ARVORE DE DECISÃO

In [143]:
tree_decision = DecisionTreeClassifier()

In [144]:
decision_tree_prev = tree_decision.fit(X_train, y_train).predict(X_test)

In [145]:
ac_decision_tree = accuracy_score(y_test, decision_tree_prev)
ac_decision_tree 

0.8131845634148838

In [146]:
confusion_matrix(y_test, decision_tree_prev)

array([[6451,  956],
       [ 869, 1493]])

RANDOM FOREST

In [147]:
random_forest = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)

In [148]:
random_forest_prev = random_forest.fit(X_train, y_train).predict(X_test)

In [149]:
ac_random_forest = accuracy_score(y_test, random_forest_prev)
ac_random_forest

0.8535162247927116

In [150]:
confusion_matrix(y_test, random_forest_prev)

array([[6858,  549],
       [ 882, 1480]])

Comparação

In [151]:
df_comparacao = pd.DataFrame(columns=['algoritmo', 'accuracy'], index=[0,1,2])

In [152]:
df_comparacao.loc[0]['algoritmo'] = 'Naive_Bayes'
df_comparacao.loc[1]['algoritmo'] = 'Decision_Tree'
df_comparacao.loc[2]['algoritmo'] = 'Random_Forest'
df_comparacao.loc[0]['accuracy'] = ac_naive
df_comparacao.loc[1]['accuracy'] = ac_decision_tree
df_comparacao.loc[2]['accuracy'] = ac_random_forest

In [153]:
df_comparacao

algoritmo  accuracy
0    Naive_Bayes   0.79742
1  Decision_Tree  0.813185
2  Random_Forest  0.853516